import Foundation
import Observation
import BulkGitHubKit

@MainActor
@Observable
final class AppModel {
    var settings = AppSettings()
    /// The selected job phase: drives what kind of script Generate requests.
    /// Kept in sync with the editor — validating or loading a script adopts
    /// its declared phase.
    var phase: JobPhase = .check
    var prompt: String = ""
    var scriptText: String = ""
    var paramsDraft: [String: String] = [:]
    /// Explicit PR title for update jobs — autogenerated when left empty,
    /// inserted into the generation prompt and overriding the script's
    /// prTitle param when set.
    var prTitle: String = ""
    /// Canary target: when set, update runs are confined to this one repo.
    var canaryRepo: String = ""
    /// Cross-phase job state (JSON per key) — written by check runs, read by
    /// update runs so they don't repeat the search.
    var jobState: [String: String] = [:]
    var quotaText: String?
    private var promptsByPhase: [JobPhase: String] = [:]
    var diagnostics: [Diagnostic] = []
    var results: [RepoResult] = []
    var logs: [String] = []
    var auditEvents: [AuditEvent] = []
    var plannedActions: [String: [PlannedAction]] = [:]
    var statusLine: String = "Ready"
    var running = false
    var generating = false
    var validating = false
    var selectedRepo: String?

    @ObservationIgnored let credentials: CredentialStore
    @ObservationIgnored private let store = AppStateStore()
    @ObservationIgnored private let engine = ScriptEngine()
    @ObservationIgnored private let rateLimit = RateLimitMonitor()
    @ObservationIgnored private var runTask: Task<Void, Never>?
    @ObservationIgnored private let typescript = TypeScriptService.loadDefault()
    @ObservationIgnored private lazy var pipeline = ValidationPipeline(typescript: typescript)

    init(credentials: CredentialStore = KeychainCredentialStore()) {
        self.credentials = credentials
        if let snapshot = store.load() {
            settings = snapshot.settings
            if let job = snapshot.job {
                phase = job.phase
                prompt = job.prompt
                scriptText = job.scriptSource
                paramsDraft = job.params
                results = job.results
                logs = job.logs
                auditEvents = job.auditEvents
                plannedActions = job.plannedActions ?? [:]
                jobState = job.state ?? [:]
                prTitle = job.prTitle ?? ""
                canaryRepo = job.canaryRepo ?? ""
                if let saved = job.promptsByPhase {
                    for (key, value) in saved {
                        if let savedPhase = JobPhase(rawValue: key) {
                            promptsByPhase[savedPhase] = value
                        }
                    }
                }
                statusLine = job.lastRunStatus ?? "Restored previous job"
            }
        }
        if scriptText.isEmpty {
            loadGoldenRecipe()
        }
    }

    var typeCheckingAvailable: Bool { typescript != nil }
    var typeCheckerLabel: String {
        guard typescript != nil else { return "Type-check unavailable" }
        if let version = typescript?.compilerVersion { return "TypeScript \(version)" }
        return "TypeScript ready"
    }

    var selectedResult: RepoResult? {
        guard let selectedRepo else { return nil }
        return results.first { $0.id == selectedRepo }
    }

    func setPhase(_ newPhase: JobPhase) {
        guard newPhase != phase else { return }
        // Prompts are per phase: an update prompt starts empty rather than
        // inheriting the check prompt.
        promptsByPhase[phase] = prompt
        phase = newPhase
        prompt = promptsByPhase[newPhase] ?? ""
        switch newPhase {
        case .check:
            statusLine = "Check phase — prompts generate read-only search scripts"
        case .update:
            statusLine = "Update phase — prompts generate dry-run update scripts (nothing reaches GitHub)"
        case .merge:
            statusLine = "Merge phase arrives in a later release"
        }
    }

    func loadRecipe(_ recipe: Recipe) {
        guard let source = recipe.source else { return }
        promptsByPhase[phase] = prompt
        scriptText = source
        phase = recipe.phase
        prompt = recipe.prompt
        promptsByPhase[recipe.phase] = recipe.prompt
        diagnostics = []
        statusLine = "Loaded recipe — Check to type-check, Run to execute"
    }

    func loadRecipe(named name: String) {
        guard let recipe = RecipeCatalog.recipe(id: name) else { return }
        loadRecipe(recipe)
    }

    func loadGoldenRecipe() {
        loadRecipe(named: "find_yaml_key_value")
    }

    // MARK: Client selection

    func githubClient() -> GitHubClient {
        if settings.useFixtureGitHub { return FixtureGitHubClient.demo() }
        let credentials = self.credentials
        return LiveGitHubClient(apiHost: settings.apiHost,
                                tokenProvider: { credentials.read(.githubToken) },
                                rateLimit: rateLimit)
    }

    private func refreshQuota() {
        quotaText = settings.useFixtureGitHub ? nil : rateLimit.display
    }

    func llmClient() -> LLMClient {
        if settings.useMockLLM { return MockLLMClient() }
        let credentials = self.credentials
        return AnthropicClient(model: settings.aiModel,
                               keyProvider: { credentials.read(.anthropicAPIKey) })
    }

    // MARK: Actions

    func generate() {
        guard !generating, !prompt.isEmpty else { return }
        generating = true
        statusLine = "Requesting script… (model thinking)"
        let client = llmClient()
        let context = ScriptGenerationContext(organisation: settings.organisation, phase: phase)
        var promptText = prompt
        if phase == .update, !prTitle.isEmpty {
            promptText += "\n\nUse exactly this pull request title: \"\(prTitle)\""
        }
        let previousScript = scriptText
        Task {
            // Stream the raw response, painting the in-progress script into
            // the editor as it is written; parse the assembled text at the end.
            var raw = ""
            do {
                for try await event in client.streamScript(prompt: promptText, context: context) {
                    guard case .delta(let chunk) = event else { continue }
                    raw += chunk
                    let live = PromptLibrary.liveScript(fromPartial: raw)
                    if !live.isEmpty { scriptText = live }
                    statusLine = "Writing script… \(raw.count) characters"
                }
                switch PromptLibrary.parseGeneration(from: raw) {
                case .script(let script) where !script.isEmpty:
                    scriptText = script
                    statusLine = "Script generated — review before running"
                    generating = false
                    await validate()
                case .script:
                    scriptText = previousScript
                    statusLine = "Generation produced no script"
                    generating = false
                case .capabilityGap(let report):
                    scriptText = previousScript
                    surfaceCapabilityGap(report)
                    generating = false
                }
            } catch LLMClientError.capabilityGap(let report) {
                scriptText = previousScript
                surfaceCapabilityGap(report)
                generating = false
            } catch {
                scriptText = previousScript
                statusLine = "Generation failed: \(error.localizedDescription)"
                generating = false
            }
        }
    }

    private func surfaceCapabilityGap(_ report: String) {
        statusLine = "Capability gap — the model needs host APIs we don't offer (details in console)"
        logs.append("◆ The model reports this request needs capabilities the host API does not provide:")
        for line in report.split(separator: "\n", omittingEmptySubsequences: false) {
            logs.append("  " + String(line))
        }
    }

    @discardableResult
    func validate() async -> ValidatedScript? {
        guard !validating else { return nil }
        validating = true
        defer { validating = false }
        statusLine = typeCheckingAvailable ? "Type-checking against bulkgh.d.ts…" : "Checking…"
        let source = scriptText
        let pipeline = self.pipeline
        do {
            let validated = try await Task.detached(priority: .userInitiated) {
                try pipeline.validate(source: source)
            }.value
            diagnostics = validated.diagnostics
            var merged = validated.meta.params
            for (key, value) in paramsDraft where merged[key] != nil {
                merged[key] = value
            }
            paramsDraft = merged
            phase = validated.meta.phase
            // Two-way sync with the explicit PR-title field: an explicit
            // title wins; otherwise the script's (auto)generated one shows.
            if !prTitle.isEmpty {
                if paramsDraft["prTitle"] != nil { paramsDraft["prTitle"] = prTitle }
            } else if let generated = paramsDraft["prTitle"] {
                prTitle = generated
            }
            statusLine = "Valid — \(validated.meta.title)"
            return validated
        } catch let error as ValidationError {
            diagnostics = error.diagnostics
            statusLine = error.errorDescription ?? "Validation failed"
            return nil
        } catch {
            statusLine = "Validation failed: \(error.localizedDescription)"
            return nil
        }
    }

    func run() {
        guard !running else { return }
        runTask = Task { await runInternal() }
    }

    private func runInternal() async {
        guard let validated = await validate() else { return }
        running = true
        defer { running = false }
        results = []
        logs = []
        auditEvents = []
        plannedActions = [:]
        selectedRepo = nil
        statusLine = "Running…"
        var params = paramsDraft
        if validated.meta.phase == .update, !prTitle.isEmpty, params["prTitle"] != nil {
            params["prTitle"] = prTitle
        }
        var configuration = EngineConfiguration(settings: settings)
        let canary = canaryRepo.trimmingCharacters(in: .whitespaces)
        if validated.meta.phase == .update, !canary.isEmpty {
            let fullName = canary.contains("/") ? canary : "\(settings.organisation)/\(canary)"
            configuration.targetRepos = [fullName]
        }
        let outcome = await engine.run(javaScript: validated.javaScript,
                                       phase: validated.meta.phase,
                                       params: params,
                                       github: githubClient(),
                                       organisation: settings.organisation,
                                       configuration: configuration,
                                       initialState: jobState) { [weak self] event in
            Task { @MainActor [weak self] in
                self?.handle(event)
            }
        }
        results = outcome.results
        logs = outcome.logs
        auditEvents = outcome.auditEvents
        plannedActions = outcome.plannedActions
        if !outcome.state.isEmpty {
            jobState.merge(outcome.state) { _, new in new }
        }
        refreshQuota()
        let plannedRepos = outcome.results.filter { $0.status == .planned }
        if let first = plannedRepos.first {
            selectedRepo = first.id
            statusLine = "Run \(outcome.status.label) — \(plannedRepos.count) repo(s) planned; dry-run diffs in the right panel"
        } else {
            statusLine = "Run \(outcome.status.label)"
        }
        saveNow()
    }

    func cancel() {
        runTask?.cancel()
        statusLine = "Cancelling…"
    }

    private func handle(_ event: RunEvent) {
        switch event {
        case .log(let line):
            logs.append(line)
        case .progress(let line):
            logs.append("▸ \(line)")
        case .repo(let result):
            if let index = results.firstIndex(where: { $0.id == result.id }) {
                results[index] = result
            } else {
                results.append(result)
            }
        case .audit(let event):
            auditEvents.append(event)
            refreshQuota()
        }
    }

    // MARK: Persistence

    func saveNow() {
        var job = Job(prompt: prompt, phase: phase)
        job.scriptSource = scriptText
        job.params = paramsDraft
        job.results = results
        job.logs = logs
        job.auditEvents = auditEvents
        job.plannedActions = plannedActions
        job.state = jobState
        job.prTitle = prTitle
        job.canaryRepo = canaryRepo
        var prompts = promptsByPhase
        prompts[phase] = prompt
        job.promptsByPhase = Dictionary(uniqueKeysWithValues: prompts.map { ($0.key.rawValue, $0.value) })
        job.lastRunStatus = statusLine
        try? store.save(AppStateSnapshot(settings: settings, job: job))
    }
}
