import Foundation
import Observation
import BulkGitHubKit

@MainActor
@Observable
final class AppModel {
    var settings = AppSettings()
    /// The selected job phase: drives what kind of script Generate requests.
    /// Kept in sync with the editor — validating or loading a script adopts
    /// its declared phase.
    var phase: JobPhase = .check
    var prompt: String = ""
    var scriptText: String = ""
    var paramsDraft: [String: String] = [:]
    /// Explicit PR title/description for update jobs — autogenerated when
    /// left empty, inserted into the generation prompt and overriding the
    /// script's prTitle/prBody params when set.
    var prTitle: String = ""
    var prBody: String = ""
    /// Canary target: when set, update runs are confined to this one repo.
    var canaryRepo: String = ""
    /// Cross-phase job state (JSON per key) — written by check runs, read by
    /// update runs so they don't repeat the search.
    var jobState: [String: String] = [:]
    var quotaText: String?
    /// Each phase is its own workspace — prompt, script, and params swap
    /// together on a phase switch, so editing the update script can never
    /// make check state look stale (and vice versa). The check → update
    /// links that remain are deliberate: carried job state and the funnel
    /// rows in the update table.
    private var promptsByPhase: [JobPhase: String] = [:]
    private var scriptsByPhase: [JobPhase: String] = [:]
    private var paramsByPhase: [JobPhase: [String: String]] = [:]
    var diagnostics: [Diagnostic] = []
    /// Results are kept per phase: switching Check ↔ Update shows each
    /// phase's own last run instead of leaking one phase's table into the
    /// other.
    private(set) var resultsByPhase: [JobPhase: [RepoResult]] = [:]
    /// The script source that produced each phase's results, for staleness:
    /// regenerating or editing the script makes existing results stale.
    private var ranScriptByPhase: [JobPhase: String] = [:]
    /// The effective params each phase's results were produced with —
    /// param edits change what the script computes just like source edits,
    /// so they trigger the same staleness.
    private var ranParamsByPhase: [JobPhase: [String: String]] = [:]
    /// The defaults declared in the script's meta.params (captured at
    /// validation), so the params bar can mark edited values and offer a
    /// reset back to the script's own default.
    private var declaredParamsByPhase: [JobPhase: [String: String]] = [:]
    var results: [RepoResult] { resultsByPhase[phase] ?? [] }
    var logs: [String] = []
    var auditEvents: [AuditEvent] = []
    /// Cumulative across all runs of this job (capped), each run prefixed
    /// with a synthetic boundary event — the job's full audit trail.
    var auditTrail: [AuditEvent] = []
    var plannedActions: [String: [PlannedAction]] = [:]
    /// The phase whose dry run produced plannedActions: the update plan must
    /// not leak into the merge phase's Apply flow (and vice versa).
    var plannedActionsPhase: JobPhase?
    /// The reviewed plan, visible only in the phase that produced it.
    var activePlan: [String: [PlannedAction]] {
        plannedActionsPhase == phase ? plannedActions : [:]
    }
    /// Remote objects armed runs of this job created (the artifact registry —
    /// merge/cancel operates only on these).
    var artifacts: [Artifact] = []
    /// Per-PR merge approvals, capturing the head SHA approved. Merging
    /// requires the head to still match — host-enforced.
    var approvals: [Approval] = []
    /// The reviewed plan as applied, per repo — what each job PR changes.
    /// Survives later dry runs (which replace the working plan) and
    /// restarts; cleared with the repo's artifacts when its PR is consumed.
    var appliedPlan: [String: [PlannedAction]] = [:]
    var statusLine: String = "Ready"
    var running = false
    /// True while an ARMED run is executing — drives the loud mode banner.
    var currentRunIsArmed = false
    var showApplySheet = false
    /// The user-set write mode for the current phase: with it OFF, Run is a
    /// dry run; with it ON, Run applies the reviewed plan (via the
    /// confirmation sheet). Snaps back to dry run after every armed run and
    /// on any context change — each write is a deliberate act, never a
    /// sticky default. Never persisted.
    var writeArmed = false
    /// Write mode requires something reviewed to apply: a plan from this
    /// phase's dry run, not invalidated by script edits.
    var canArmWrites: Bool {
        phase != .check && !activePlan.isEmpty && !resultsAreStale
    }
    var generating = false
    var validating = false
    var selectedRepo: String?

    @ObservationIgnored let credentials: CredentialStore
    @ObservationIgnored private let store = AppStateStore()
    @ObservationIgnored private let engine = ScriptEngine()
    @ObservationIgnored private let rateLimit = RateLimitMonitor()
    @ObservationIgnored private var runTask: Task<Void, Never>?
    /// In-flight validation, joinable: Run during the post-generation
    /// auto-validate waits for that result instead of silently bailing.
    @ObservationIgnored private var validationTask: Task<ValidatedScript?, Never>?
    /// Bumped per run; engine events carry the generation they belong to, so
    /// stragglers arriving after the final snapshot can't re-append stale rows
    /// or duplicate log lines.
    @ObservationIgnored private var runGeneration = 0
    @ObservationIgnored private let typescript = TypeScriptService.loadDefault()
    @ObservationIgnored private lazy var pipeline = ValidationPipeline(typescript: typescript)

    init(credentials: CredentialStore = KeychainCredentialStore()) {
        self.credentials = credentials
        var restoredJob = false
        if let snapshot = store.load() {
            settings = snapshot.settings
            if let job = snapshot.job {
                restoredJob = true
                phase = job.phase
                promptsByPhase = Self.byPhase(job.promptsByPhase)
                scriptsByPhase = Self.byPhase(job.scriptsByPhase)
                paramsByPhase = Self.byPhase(job.paramsByPhase)
                resultsByPhase = Self.byPhase(job.resultsByPhase)
                ranScriptByPhase = Self.byPhase(job.ranScriptByPhase)
                ranParamsByPhase = Self.byPhase(job.ranParamsByPhase)
                declaredParamsByPhase = Self.byPhase(job.declaredParamsByPhase)
                // Pre-per-phase saves: attribute the legacy single slots to
                // the job's phase.
                if scriptsByPhase.isEmpty { scriptsByPhase[job.phase] = job.scriptSource }
                if paramsByPhase.isEmpty { paramsByPhase[job.phase] = job.params }
                if promptsByPhase.isEmpty { promptsByPhase[job.phase] = job.prompt }
                if resultsByPhase.isEmpty, !job.results.isEmpty {
                    resultsByPhase[job.phase] = job.results
                    ranScriptByPhase[job.phase] = job.scriptSource
                }
                prompt = promptsByPhase[job.phase] ?? ""
                scriptText = scriptsByPhase[job.phase] ?? ""
                paramsDraft = paramsByPhase[job.phase] ?? [:]
                logs = job.logs
                auditEvents = job.auditEvents
                auditTrail = job.auditTrail ?? []
                plannedActions = job.plannedActions ?? [:]
                plannedActionsPhase = job.planPhase.flatMap(JobPhase.init(rawValue:))
                    ?? (plannedActions.isEmpty ? nil : .update)  // legacy saves were update-only
                jobState = job.state ?? [:]
                prTitle = job.prTitle ?? ""
                prBody = job.prBody ?? ""
                canaryRepo = job.canaryRepo ?? ""
                artifacts = job.artifacts ?? []
                approvals = job.approvals ?? []
                appliedPlan = job.appliedPlans ?? [:]
                statusLine = job.lastRunStatus ?? "Restored previous job"
            }
        }
        if !restoredJob {
            loadGoldenRecipe()
        }
        userRecipes = recipeStore.load()
    }

    private static func byPhase<T>(_ raw: [String: T]?) -> [JobPhase: T] {
        guard let raw else { return [:] }
        var mapped: [JobPhase: T] = [:]
        for (key, value) in raw {
            if let phase = JobPhase(rawValue: key) { mapped[phase] = value }
        }
        return mapped
    }

    private static func rawKeyed<T>(_ map: [JobPhase: T]) -> [String: T] {
        Dictionary(uniqueKeysWithValues: map.map { ($0.key.rawValue, $0.value) })
    }

    var typeCheckingAvailable: Bool { typescript != nil }
    var typeCheckerLabel: String {
        guard typescript != nil else { return "Type-check unavailable" }
        if let version = typescript?.compilerVersion { return "TypeScript \(version)" }
        return "TypeScript ready"
    }

    /// Params shown in the editable strip — PR title/description have
    /// dedicated fields, so their raw params stay hidden.
    var visibleParamKeys: [String] {
        paramsDraft.keys.filter { $0 != "prTitle" && $0 != "prBody" }.sorted()
    }

    var selectedResult: RepoResult? {
        guard let selectedRepo else { return nil }
        if let result = results.first(where: { $0.id == selectedRepo }) { return result }
        // The update table carries check rows forward before any update run —
        // selecting one inspects its check evidence.
        if phase == .update {
            return resultsByPhase[.check]?.first { $0.id == selectedRepo }
        }
        // Merge rows exist before any merge run: selecting one inspects the
        // PR's receipts. "PR raised" is the true state of an artifact row.
        if phase == .merge, let row = mergeRows.first(where: { $0.id == selectedRepo }) {
            return row.result ?? RepoResult(repo: row.repo, status: .prRaised,
                                            reason: "PR \(row.artifact.name) awaiting merge")
        }
        return nil
    }

    /// The visible results were produced by a different script — or different
    /// params — than what's on screen now. Suppressed while generating or
    /// running: the script is mid-change then, so "stale" is noise; it
    /// reappears once the new script settles unrun. Starting a run clears
    /// the results, so the banner is gone the moment Run is pressed.
    var resultsAreStale: Bool { staleReason != nil }

    /// What changed since the visible results were produced (nil = nothing).
    var staleReason: String? {
        guard !generating, !running,
              !results.isEmpty, let ran = ranScriptByPhase[phase] else { return nil }
        let scriptChanged = ran != scriptText
        // Restored pre-0.4.5 state has no recorded params: unknown, not stale.
        let paramsChanged = ranParamsByPhase[phase].map { $0 != effectiveParams(for: phase) } ?? false
        switch (scriptChanged, paramsChanged) {
        case (true, true): return "The script and its parameters have changed since these results were produced — Run to refresh."
        case (true, false): return "The script has changed since these results were produced — Run to refresh."
        case (false, true): return "The parameters have changed since these results were produced — Run to refresh."
        case (false, false): return nil
        }
    }

    /// The params a run of `runPhase` would receive right now: the editable
    /// draft, with the explicit PR title/description fields winning where
    /// the script declares those params. Mirrored by runInternal.
    private func effectiveParams(for runPhase: JobPhase) -> [String: String] {
        var params = paramsDraft
        if runPhase == .update, !prTitle.isEmpty, params["prTitle"] != nil {
            params["prTitle"] = prTitle
        }
        if runPhase == .update, !prBody.isEmpty, params["prBody"] != nil {
            params["prBody"] = prBody
        }
        return params
    }

    /// The script's own default for a param (nil when unknown — e.g. the
    /// script hasn't been validated since it changed).
    func declaredDefault(for key: String) -> String? {
        declaredParamsByPhase[phase]?[key]
    }

    /// One row of the update table: the check verdict and the update outcome
    /// side by side, so the funnel (found by Check → planned by Update) is
    /// visible from the moment you switch phases — including the canary repo,
    /// before any update run has happened.
    struct UpdateRow: Identifiable {
        let repo: RepoRef
        let check: RepoResult?
        let update: RepoResult?
        var id: String { repo.fullName }
    }

    /// One row of the merge table: a job PR artifact, its approval state,
    /// and any merge-run outcome.
    struct MergeRow: Identifiable {
        let artifact: Artifact
        let repo: RepoRef
        let number: Int
        let approved: Bool
        let result: RepoResult?
        var id: String { artifact.repo }
    }

    var mergeRows: [MergeRow] {
        let results = resultsByPhase[.merge] ?? []
        // One row per repo, latest artifact wins — stale registry entries
        // from an earlier session must not produce duplicate rows.
        var byRepo: [String: MergeRow] = [:]
        var order: [String] = []
        for artifact in artifacts where artifact.kind == .pullRequest {
            guard let number = Int(artifact.name.dropFirst()) else { continue }
            if byRepo[artifact.repo] == nil { order.append(artifact.repo) }
            let result = results.first { $0.id == artifact.repo }
            byRepo[artifact.repo] = MergeRow(
                artifact: artifact,
                repo: result?.repo ?? RepoRef(fullName: artifact.repo),
                number: number,
                approved: approvals.contains {
                    $0.repo == artifact.repo && $0.prNumber == number
                },
                result: result)
        }
        return order.compactMap { byRepo[$0] }
    }

    /// Approve every job PR that isn't yet approved, capturing each current
    /// head SHA.
    func approveAll() {
        let pending = mergeRows.filter { !$0.approved }
        guard !pending.isEmpty else { return }
        let client = githubClient()
        Task {
            var added = 0
            for row in pending {
                do {
                    let pr = try await client.getPR(repo: row.artifact.repo, number: row.number)
                    approvals.append(Approval(repo: row.artifact.repo,
                                              prNumber: row.number, headSha: pr.headSha))
                    added += 1
                } catch {
                    statusLine = "Could not approve PR #\(row.number) in \(row.artifact.repo): \(error.localizedDescription)"
                }
            }
            if added > 0 {
                statusLine = "Approved \(added) PR(s) — merging requires each head to still match"
                saveNow()
            }
        }
    }

    func clearApprovals() {
        guard !approvals.isEmpty else { return }
        approvals.removeAll()
        statusLine = "All approvals withdrawn"
        saveNow()
    }

    /// Approve (capturing the current head SHA) or withdraw approval.
    func toggleApproval(repo: String, prNumber: Int) {
        if let index = approvals.firstIndex(where: { $0.repo == repo && $0.prNumber == prNumber }) {
            approvals.remove(at: index)
            statusLine = "Approval withdrawn for PR #\(prNumber) in \(repo)"
            saveNow()
            return
        }
        let client = githubClient()
        Task {
            do {
                let pr = try await client.getPR(repo: repo, number: prNumber)
                approvals.append(Approval(repo: repo, prNumber: prNumber, headSha: pr.headSha))
                statusLine = "Approved PR #\(prNumber) in \(repo) at \(String(pr.headSha.prefix(12))) — merging requires the head to still match"
                saveNow()
            } catch {
                statusLine = "Could not approve PR #\(prNumber): \(error.localizedDescription)"
            }
        }
    }

    var updateRows: [UpdateRow] {
        let checks = resultsByPhase[.check] ?? []
        let updates = resultsByPhase[.update] ?? []
        var updatesByID = Dictionary(uniqueKeysWithValues: updates.map { ($0.id, $0) })
        var rows: [UpdateRow] = checks.map { check in
            let update = updatesByID.removeValue(forKey: check.id)
            return UpdateRow(repo: update?.repo ?? check.repo, check: check, update: update)
        }
        // Repos only the update run touched (e.g. a full scan with no carried
        // check results), in run order.
        for result in updates where updatesByID[result.id] != nil {
            rows.append(UpdateRow(repo: result.repo, check: nil, update: result))
        }
        return rows
    }

    /// Row count for the status footer — the update table includes carried
    /// check rows, and the merge table shows registry PRs.
    var visibleRowCount: Int {
        switch phase {
        case .check: return results.count
        case .update: return updateRows.count
        case .merge: return mergeRows.count
        }
    }

    /// Switching between fixture data and live GitHub is switching WORLDS:
    /// results, plans, artifacts, approvals, and carried state from the old
    /// world are meaningless in the new one (fixture PR receipts point at
    /// nothing real, and vice versa). Workspaces — prompts, scripts, params —
    /// survive; they are world-independent.
    func dataSourceChanged() {
        guard !running else { return }
        resultsByPhase = [:]
        ranScriptByPhase = [:]
        ranParamsByPhase = [:]
        plannedActions = [:]
        plannedActionsPhase = nil
        artifacts = []
        approvals = []
        appliedPlan = [:]
        jobState = [:]
        selectedRepo = nil
        canaryRepo = ""
        quotaText = nil
        logs = []
        auditEvents = []
        auditTrail = []
        writeArmed = false
        statusLine = settings.useFixtureGitHub
            ? "Switched to fixture data — workflow state cleared, scripts kept"
            : "Switched to LIVE GitHub — workflow state cleared, scripts kept"
        saveNow()
    }

    // MARK: New job (File > New Job…, ⌘N)

    /// Drives the confirmation alert — New Job always confirms before
    /// discarding, since it wipes every phase's workspace and history.
    var showNewJobConfirmation = false
    /// Drives the refusal alert when the artifact registry is non-empty.
    var showNewJobBlocked = false

    func requestNewJob() {
        guard !running, !generating, !validating else { return }
        // Wiping the registry would orphan the branches/PRs this job
        // created: the registry is the only authority merge/cancel has, so
        // nothing could ever touch them again. Refuse, pointing at the
        // merge/cancel path, rather than confirm-through.
        if !artifacts.isEmpty {
            showNewJobBlocked = true
        } else {
            showNewJobConfirmation = true
        }
    }

    /// Discard the entire job — all three phase workspaces, results, plans,
    /// logs, the audit trail, and carried job state — leaving an empty
    /// workspace. (First launch loads the golden recipe for discoverability;
    /// New Job deliberately does not — the library is one click away, and a
    /// "new" workspace with a pre-filled script reads as "didn't clear".)
    /// Settings and credentials survive. Reached only via requestNewJob's
    /// confirmation.
    func startNewJob() {
        guard !running, !generating, artifacts.isEmpty else { return }
        phase = .check
        prompt = ""
        scriptText = ""
        paramsDraft = [:]
        prTitle = ""
        prBody = ""
        canaryRepo = ""
        jobState = [:]
        promptsByPhase = [:]
        scriptsByPhase = [:]
        paramsByPhase = [:]
        diagnostics = []
        resultsByPhase = [:]
        ranScriptByPhase = [:]
        ranParamsByPhase = [:]
        declaredParamsByPhase = [:]
        logs = []
        auditEvents = []
        auditTrail = []
        plannedActions = [:]
        plannedActionsPhase = nil
        approvals = []
        appliedPlan = [:]
        selectedRepo = nil
        writeArmed = false
        quotaText = nil
        statusLine = "New job — describe what to find, or load a recipe"
        saveNow()
    }

    func clearResults() {
        resultsByPhase[phase] = []
        ranScriptByPhase[phase] = nil
        ranParamsByPhase[phase] = nil
        if plannedActionsPhase == phase {
            plannedActions = [:]
            plannedActionsPhase = nil
        }
        selectedRepo = nil
        statusLine = "Results cleared"
    }

    func useAsCanary(_ repoID: String) {
        canaryRepo = repoID
        setPhase(.update)
        selectedRepo = repoID
        statusLine = "Canary set — update runs are confined to \(repoID)"
    }

    func setPhase(_ newPhase: JobPhase) {
        guard newPhase != phase, !running, !generating else { return }
        // Each phase is a separate workspace: prompt, script, and params swap
        // together. An update workspace starts empty rather than inheriting
        // the check script.
        stashWorkspace()
        phase = newPhase
        restoreWorkspace()
        writeArmed = false
        switch newPhase {
        case .check:
            statusLine = "Check phase — prompts generate read-only search scripts"
        case .update:
            statusLine = "Update phase — prompts generate dry-run update scripts (nothing reaches GitHub)"
        case .merge:
            statusLine = "Merge phase — approve job PRs in the table, then dry-run a merge script (it can only touch this job's PRs and branches)"
        }
    }

    private func stashWorkspace() {
        promptsByPhase[phase] = prompt
        scriptsByPhase[phase] = scriptText
        paramsByPhase[phase] = paramsDraft
    }

    private func restoreWorkspace() {
        prompt = promptsByPhase[phase] ?? ""
        scriptText = scriptsByPhase[phase] ?? ""
        paramsDraft = paramsByPhase[phase] ?? [:]
        diagnostics = []
    }

    func loadRecipe(_ recipe: Recipe) {
        guard let source = recipe.source, !running, !generating else { return }
        if recipe.phase != phase {
            stashWorkspace()
            phase = recipe.phase
        }
        writeArmed = false
        scriptText = source
        prompt = recipe.prompt
        promptsByPhase[recipe.phase] = recipe.prompt
        scriptsByPhase[recipe.phase] = source
        // The params belong to the script: a replaced script means a fresh
        // draft (and fresh declared defaults), not the previous script's
        // values lingering in the bar.
        paramsDraft = [:]
        paramsByPhase[recipe.phase] = [:]
        declaredParamsByPhase[recipe.phase] = nil
        diagnostics = []
        statusLine = "Loaded \"\(recipe.title)\""
        // Validate right away so the param bar repopulates from the recipe's
        // meta.params without waiting for a manual Check. Any in-flight
        // validation of the replaced script must fully drain first (its
        // results are discarded by the stale-source guard) — validate()
        // would otherwise JOIN it and return the old script's result.
        Task { [weak self] in
            while let task = self?.validationTask {
                _ = await task.value
                await Task.yield()
            }
            await self?.validate()
        }
    }

    func loadRecipe(named name: String) {
        guard let recipe = RecipeCatalog.recipe(id: name) else { return }
        loadRecipe(recipe)
    }

    // MARK: User recipes (saved from the workspace, file-backed)

    @ObservationIgnored private let recipeStore = UserRecipeStore()
    private(set) var userRecipes: [UserRecipe] = []

    /// Drives the save-as-recipe name prompt; recipeNameDraft backs the
    /// rename prompt too.
    var showSaveRecipePrompt = false
    var recipeNameDraft = ""
    var renamingRecipe: UserRecipe?
    var deletingRecipe: UserRecipe?

    func requestSaveRecipe() {
        guard !scriptText.isEmpty else {
            statusLine = "Nothing to save — the editor is empty"
            return
        }
        recipeNameDraft = ""
        showSaveRecipePrompt = true
    }

    /// Capture the current workspace — prompt, script, phase — under the
    /// drafted name.
    func saveCurrentAsRecipe() {
        let title = recipeNameDraft.trimmingCharacters(in: .whitespaces)
        guard !title.isEmpty, !scriptText.isEmpty else { return }
        do {
            try recipeStore.save(UserRecipe(title: title, prompt: prompt,
                                            phase: phase, source: scriptText))
            userRecipes = recipeStore.load()
            statusLine = "Saved recipe \"\(title)\""
        } catch {
            statusLine = "Could not save recipe: \(error.localizedDescription)"
        }
    }

    func renameRecipe(_ recipe: UserRecipe) {
        let title = recipeNameDraft.trimmingCharacters(in: .whitespaces)
        guard !title.isEmpty, title != recipe.title else { return }
        var renamed = recipe
        renamed.title = title
        do {
            try recipeStore.save(renamed)
            userRecipes = recipeStore.load()
            statusLine = "Renamed recipe to \"\(title)\""
        } catch {
            statusLine = "Could not rename recipe: \(error.localizedDescription)"
        }
    }

    func deleteRecipe(_ recipe: UserRecipe) {
        do {
            try recipeStore.delete(id: recipe.id)
            userRecipes = recipeStore.load()
            statusLine = "Deleted recipe \"\(recipe.title)\""
        } catch {
            statusLine = "Could not delete recipe: \(error.localizedDescription)"
        }
    }

    func loadGoldenRecipe() {
        loadRecipe(named: "find_file_missing_string")
    }

    // MARK: Client selection

    /// ONE fixture instance per app session: armed-run writes (branches, PRs)
    /// must survive into the merge phase or the loop can't be rehearsed —
    /// a fresh demo() per call silently discarded them.
    @ObservationIgnored private lazy var fixtureClient = FixtureGitHubClient.demo()

    func githubClient() -> GitHubClient {
        if settings.useFixtureGitHub { return fixtureClient }
        let credentials = self.credentials
        return LiveGitHubClient(apiHost: settings.apiHost,
                                tokenProvider: { credentials.read(.githubToken) },
                                rateLimit: rateLimit)
    }

    private func refreshQuota() {
        quotaText = settings.useFixtureGitHub ? nil : rateLimit.display
    }

    func llmClient() -> LLMClient {
        if settings.useMockLLM { return MockLLMClient() }
        let credentials = self.credentials
        return AnthropicClient(model: settings.aiModel,
                               keyProvider: { credentials.read(.anthropicAPIKey) })
    }

    // MARK: Actions

    func generate() {
        guard !generating, !prompt.isEmpty else { return }
        generating = true
        statusLine = "Requesting script… (model thinking)"
        let client = llmClient()
        let context = ScriptGenerationContext(organisation: settings.organisation, phase: phase)
        var promptText = prompt
        if phase == .update, !prTitle.isEmpty {
            promptText += "\n\nUse exactly this pull request title: \"\(prTitle)\""
        }
        if phase == .update, !prBody.isEmpty {
            promptText += "\n\nUse exactly this pull request description: \"\(prBody)\""
        }
        let previousScript = scriptText
        Task {
            // Stream the raw response, painting the in-progress script into
            // the editor as it is written; parse the assembled text at the end.
            var raw = ""
            do {
                for try await event in client.streamScript(prompt: promptText, context: context) {
                    guard case .delta(let chunk) = event else { continue }
                    raw += chunk
                    let live = PromptLibrary.liveScript(fromPartial: raw)
                    if !live.isEmpty { scriptText = live }
                    statusLine = "Writing script… \(raw.count) characters"
                }
                switch PromptLibrary.parseGeneration(from: raw) {
                case .script(let script) where !script.isEmpty:
                    scriptText = script
                    // A generated script replaces the old one wholesale, so
                    // its declared params must win — stale draft values from
                    // the previous script would override what the model just
                    // wrote (e.g. values it patched in from the prompt).
                    paramsDraft = [:]
                    declaredParamsByPhase[phase] = nil
                    statusLine = "Script generated — review before running"
                    generating = false
                    await validate()
                case .script:
                    scriptText = previousScript
                    statusLine = "Generation produced no script"
                    generating = false
                case .capabilityGap(let report):
                    scriptText = previousScript
                    surfaceCapabilityGap(report)
                    generating = false
                }
            } catch LLMClientError.capabilityGap(let report) {
                scriptText = previousScript
                surfaceCapabilityGap(report)
                generating = false
            } catch {
                scriptText = previousScript
                statusLine = "Generation failed: \(error.localizedDescription)"
                generating = false
            }
        }
    }

    private func surfaceCapabilityGap(_ report: String) {
        statusLine = "Capability gap — the model needs host APIs we don't offer (details in console)"
        logs.append("◆ The model reports this request needs capabilities the host API does not provide:")
        for line in report.split(separator: "\n", omittingEmptySubsequences: false) {
            logs.append("  " + String(line))
        }
    }

    @discardableResult
    func validate() async -> ValidatedScript? {
        // Join an in-flight validation (e.g. the auto-validate right after
        // generation) instead of bailing with nil — the silent nil made Run
        // a no-op the first time after regenerating a script.
        if let task = validationTask { return await task.value }
        let task = Task { await performValidation() }
        validationTask = task
        let result = await task.value
        validationTask = nil
        return result
    }

    private func performValidation() async -> ValidatedScript? {
        validating = true
        defer { validating = false }
        statusLine = typeCheckingAvailable ? "Type-checking against bulkgh.d.ts…" : "Checking…"
        let source = scriptText
        let pipeline = self.pipeline
        do {
            let validated = try await Task.detached(priority: .userInitiated) {
                try pipeline.validate(source: source)
            }.value
            // The editor moved on mid-validation (recipe load, regenerate):
            // this result describes a script that is no longer on screen.
            guard source == scriptText else { return nil }
            diagnostics = validated.diagnostics
            var merged = validated.meta.params
            for (key, value) in paramsDraft where merged[key] != nil {
                merged[key] = value
            }
            paramsDraft = merged
            // A script declaring a different phase moves there WITH the
            // current buffer (no workspace swap): the script, prompt, and
            // params on screen belong to the declared phase now.
            phase = validated.meta.phase
            declaredParamsByPhase[validated.meta.phase] = validated.meta.params
            // Two-way sync with the explicit PR title/description fields: an
            // explicit value wins; otherwise the script's generated one shows.
            if !prTitle.isEmpty {
                if paramsDraft["prTitle"] != nil { paramsDraft["prTitle"] = prTitle }
            } else if let generated = paramsDraft["prTitle"] {
                prTitle = generated
            }
            if !prBody.isEmpty {
                if paramsDraft["prBody"] != nil { paramsDraft["prBody"] = prBody }
            } else if let generated = paramsDraft["prBody"] {
                prBody = generated
            }
            statusLine = "Valid — \(validated.meta.title)"
            return validated
        } catch let error as ValidationError {
            guard source == scriptText else { return nil }
            diagnostics = error.diagnostics
            statusLine = error.errorDescription ?? "Validation failed"
            return nil
        } catch {
            guard source == scriptText else { return nil }
            statusLine = "Validation failed: \(error.localizedDescription)"
            return nil
        }
    }

    func run() {
        guard !running, !generating else { return }
        runTask = Task { await runInternal() }
    }

    /// Re-run the reviewed dry-run plan with writes ARMED for the selected
    /// repos. The engine enforces plan conformance and the drift guard;
    /// in live mode this REALLY writes to GitHub — the Apply sheet is the
    /// explicit confirmation step.
    func applyPlan(to repoIDs: Set<String>) {
        guard !running, !generating, phase == .update || phase == .merge else { return }
        guard !repoIDs.isEmpty, !plannedActions.isEmpty,
              plannedActionsPhase == phase else { return }
        runTask = Task { await runInternal(writeMode: .armed, armedTargets: repoIDs) }
    }

    private func runInternal(writeMode: EngineConfiguration.WriteMode = .dryRun,
                             armedTargets: Set<String> = []) async {
        guard let validated = await validate() else { return }
        running = true
        currentRunIsArmed = (writeMode == .armed)
        defer {
            running = false
            currentRunIsArmed = false
            // Write mode is per-run: it never survives the run that used it
            // (or a dry run started while it was somehow on).
            writeArmed = false
        }
        let runPhase = validated.meta.phase
        let runScript = scriptText
        // A fresh check starts a fresh funnel: the canary, the update
        // results, and the dry-run plan were all derived from the check
        // results this run replaces — carrying them forward made the update
        // table open on outdated statuses (and a misleading stale banner).
        // The update SCRIPT survives; it is reusable against the new results.
        // The artifact registry is never cleared — those are receipts for
        // things armed runs really created.
        if runPhase == .check {
            canaryRepo = ""
            resultsByPhase[.update] = []
            ranScriptByPhase[.update] = nil
            ranParamsByPhase[.update] = nil
            plannedActions = [:]
            plannedActionsPhase = nil
        }
        runGeneration += 1
        let generation = runGeneration
        resultsByPhase[runPhase] = []
        logs = []
        auditEvents = []
        // The reviewed plan survives an armed run — it is the reference the
        // engine checked the writes against.
        if runPhase != .check, writeMode == .dryRun {
            plannedActions = [:]
            plannedActionsPhase = nil
        }
        statusLine = writeMode == .armed ? "ARMED — applying the reviewed plan…" : "Running…"
        let params = effectiveParams(for: runPhase)
        var configuration = EngineConfiguration(settings: settings)
        if writeMode == .armed {
            configuration.writeMode = .armed
            configuration.targetRepos = armedTargets
            configuration.referencePlan = plannedActions
        } else {
            let canary = canaryRepo.trimmingCharacters(in: .whitespaces)
            if runPhase == .update, !canary.isEmpty {
                let fullName = canary.contains("/") ? canary : "\(settings.organisation)/\(canary)"
                configuration.targetRepos = [fullName]
            }
        }
        if runPhase == .merge || writeMode == .armed {
            // The job's receipts: merge scripts are scoped to them, and
            // armed update runs use them to RESUME safely onto branches/PRs
            // this job created earlier (never onto anyone else's).
            configuration.artifactRegistry = artifacts
        }
        if runPhase == .merge {
            configuration.approvals = approvals
        }
        let outcome = await engine.run(javaScript: validated.javaScript,
                                       phase: runPhase,
                                       params: params,
                                       github: githubClient(),
                                       organisation: settings.organisation,
                                       configuration: configuration,
                                       initialState: jobState) { [weak self] event in
            Task { @MainActor [weak self] in
                guard let self, self.runGeneration == generation else { return }
                self.handle(event, phase: runPhase)
            }
        }
        // Retire stragglers before installing the final snapshot — a late
        // event hopping onto the main actor afterwards would duplicate rows
        // or log lines.
        runGeneration += 1
        resultsByPhase[runPhase] = outcome.results
        ranScriptByPhase[runPhase] = runScript
        ranParamsByPhase[runPhase] = params
        logs = outcome.logs
        auditEvents = outcome.auditEvents
        // The cumulative trail: boundary event, then the run's events.
        let mode = writeMode == .armed ? "ARMED"
            : (runPhase == .check ? "read-only" : "dry run")
        auditTrail.append(AuditEvent(kind: "run", repo: nil,
                                     detail: "\(runPhase.rawValue) (\(mode), \(settings.useFixtureGitHub ? "fixture" : "live")) — \(outcome.status.label)"))
        auditTrail.append(contentsOf: outcome.auditEvents)
        if auditTrail.count > 5000 {
            auditTrail.removeFirst(auditTrail.count - 5000)
        }
        if runPhase != .check, writeMode == .dryRun {
            plannedActions = outcome.plannedActions
            plannedActionsPhase = outcome.plannedActions.isEmpty ? nil : runPhase
        }
        // Replace rather than accumulate: re-applying after a halt (or in a
        // fresh fixture session) must not leave duplicate receipts for the
        // same branch or PR.
        for artifact in outcome.artifacts {
            artifacts.removeAll {
                $0.kind == artifact.kind && $0.repo == artifact.repo && $0.name == artifact.name
            }
            artifacts.append(artifact)
        }
        // The receipts behind each PR: what the armed update actually wrote,
        // per repo — shown in the merge phase as "what this PR changes".
        // Fresh PRs also supersede any previous merge-phase outcomes: an old
        // "merged" badge must not attach to a new PR.
        if writeMode == .armed, runPhase == .update {
            for result in outcome.results where result.status == .prRaised {
                appliedPlan[result.id] = plannedActions[result.id]
            }
            resultsByPhase[.merge] = []
            ranScriptByPhase[.merge] = nil
            ranParamsByPhase[.merge] = nil
        }
        // A merged or cancelled repo's artifacts are consumed: its PR is no
        // longer open and its branch is gone — drop them (and their
        // approvals and applied plan) from the registry. The audit trail
        // keeps the history.
        if writeMode == .armed, runPhase == .merge {
            let consumed = Set(outcome.results
                .filter { [.merged, .cancelled].contains($0.status) }
                .map(\.id))
            if !consumed.isEmpty {
                artifacts.removeAll { consumed.contains($0.repo) }
                approvals.removeAll { consumed.contains($0.repo) }
                for repo in consumed { appliedPlan.removeValue(forKey: repo) }
            }
        }
        if !outcome.state.isEmpty {
            jobState.merge(outcome.state) { _, new in new }
        }
        refreshQuota()
        if let quotaText {
            logs.append("◆ GitHub \(quotaText) requests remaining")
        }
        if writeMode == .armed {
            let acted = outcome.results.filter {
                [.prRaised, .merged, .cancelled].contains($0.status)
            }
            let halted = outcome.results.filter {
                [.conflicted, .branchExists, .prExists, .blocked].contains($0.status)
            }
            if selectedRepo == nil { selectedRepo = acted.first?.id }
            let verb = runPhase == .merge ? "PR(s) merged or closed" : "PR(s) raised"
            var summary = "ARMED run \(outcome.status.label) — \(acted.count) \(verb)"
            if !halted.isEmpty { summary += ", \(halted.count) halted (see results)" }
            statusLine = summary
        } else {
            let plannedRepos = outcome.results.filter { $0.status == .planned }
            if !plannedRepos.isEmpty {
                // Keep the user's selection (e.g. the canary they were
                // inspecting); only auto-select when nothing was chosen.
                if selectedRepo == nil { selectedRepo = plannedRepos.first?.id }
                statusLine = "Run \(outcome.status.label) — \(plannedRepos.count) repo(s) planned; dry-run diffs in the right panel"
            } else {
                statusLine = "Run \(outcome.status.label)"
            }
        }
        saveNow()
    }

    func cancel() {
        runTask?.cancel()
        statusLine = "Cancelling…"
    }

    private func handle(_ event: RunEvent, phase runPhase: JobPhase) {
        switch event {
        case .log(let line):
            logs.append(line)
        case .progress(let line):
            logs.append("▸ \(line)")
        case .repo(let result):
            var rows = resultsByPhase[runPhase] ?? []
            if let index = rows.firstIndex(where: { $0.id == result.id }) {
                rows[index] = result
            } else {
                rows.append(result)
            }
            resultsByPhase[runPhase] = rows
        case .audit(let event):
            auditEvents.append(event)
            refreshQuota()
        }
    }

    // MARK: Persistence

    func saveNow() {
        stashWorkspace()
        var job = Job(prompt: prompt, phase: phase)
        job.scriptSource = scriptText
        job.params = paramsDraft
        job.results = results
        job.resultsByPhase = Self.rawKeyed(resultsByPhase)
        job.ranScriptByPhase = Self.rawKeyed(ranScriptByPhase)
        job.ranParamsByPhase = Self.rawKeyed(ranParamsByPhase)
        job.declaredParamsByPhase = Self.rawKeyed(declaredParamsByPhase)
        job.scriptsByPhase = Self.rawKeyed(scriptsByPhase)
        job.paramsByPhase = Self.rawKeyed(paramsByPhase)
        job.logs = logs
        job.auditEvents = auditEvents
        job.auditTrail = auditTrail
        job.plannedActions = plannedActions
        job.planPhase = plannedActionsPhase?.rawValue
        job.state = jobState
        job.prTitle = prTitle
        job.prBody = prBody
        job.canaryRepo = canaryRepo
        job.artifacts = artifacts
        job.approvals = approvals
        job.appliedPlans = appliedPlan
        job.promptsByPhase = Self.rawKeyed(promptsByPhase)
        job.lastRunStatus = statusLine
        try? store.save(AppStateSnapshot(settings: settings, job: job))
    }
}
