import Foundation
import Observation
import BulkGitHubKit

@MainActor
@Observable
final class AppModel {
    var settings = AppSettings()
    /// The selected job phase: drives what kind of script Generate requests.
    /// Kept in sync with the editor — validating or loading a script adopts
    /// its declared phase.
    var phase: JobPhase = .check
    var prompt: String = ""
    var scriptText: String = ""
    var paramsDraft: [String: String] = [:]
    /// Explicit PR title for update jobs — autogenerated when left empty,
    /// inserted into the generation prompt and overriding the script's
    /// prTitle param when set.
    var prTitle: String = ""
    /// Canary target: when set, update runs are confined to this one repo.
    var canaryRepo: String = ""
    /// Cross-phase job state (JSON per key) — written by check runs, read by
    /// update runs so they don't repeat the search.
    var jobState: [String: String] = [:]
    var quotaText: String?
    /// Each phase is its own workspace — prompt, script, and params swap
    /// together on a phase switch, so editing the update script can never
    /// make check state look stale (and vice versa). The check → update
    /// links that remain are deliberate: carried job state and the funnel
    /// rows in the update table.
    private var promptsByPhase: [JobPhase: String] = [:]
    private var scriptsByPhase: [JobPhase: String] = [:]
    private var paramsByPhase: [JobPhase: [String: String]] = [:]
    var diagnostics: [Diagnostic] = []
    /// Results are kept per phase: switching Check ↔ Update shows each
    /// phase's own last run instead of leaking one phase's table into the
    /// other.
    private(set) var resultsByPhase: [JobPhase: [RepoResult]] = [:]
    /// The script source that produced each phase's results, for staleness:
    /// regenerating or editing the script makes existing results stale.
    private var ranScriptByPhase: [JobPhase: String] = [:]
    var results: [RepoResult] { resultsByPhase[phase] ?? [] }
    var logs: [String] = []
    var auditEvents: [AuditEvent] = []
    var plannedActions: [String: [PlannedAction]] = [:]
    var statusLine: String = "Ready"
    var running = false
    var generating = false
    var validating = false
    var selectedRepo: String?

    @ObservationIgnored let credentials: CredentialStore
    @ObservationIgnored private let store = AppStateStore()
    @ObservationIgnored private let engine = ScriptEngine()
    @ObservationIgnored private let rateLimit = RateLimitMonitor()
    @ObservationIgnored private var runTask: Task<Void, Never>?
    /// In-flight validation, joinable: Run during the post-generation
    /// auto-validate waits for that result instead of silently bailing.
    @ObservationIgnored private var validationTask: Task<ValidatedScript?, Never>?
    /// Bumped per run; engine events carry the generation they belong to, so
    /// stragglers arriving after the final snapshot can't re-append stale rows
    /// or duplicate log lines.
    @ObservationIgnored private var runGeneration = 0
    @ObservationIgnored private let typescript = TypeScriptService.loadDefault()
    @ObservationIgnored private lazy var pipeline = ValidationPipeline(typescript: typescript)

    init(credentials: CredentialStore = KeychainCredentialStore()) {
        self.credentials = credentials
        var restoredJob = false
        if let snapshot = store.load() {
            settings = snapshot.settings
            if let job = snapshot.job {
                restoredJob = true
                phase = job.phase
                promptsByPhase = Self.byPhase(job.promptsByPhase)
                scriptsByPhase = Self.byPhase(job.scriptsByPhase)
                paramsByPhase = Self.byPhase(job.paramsByPhase)
                resultsByPhase = Self.byPhase(job.resultsByPhase)
                ranScriptByPhase = Self.byPhase(job.ranScriptByPhase)
                // Pre-per-phase saves: attribute the legacy single slots to
                // the job's phase.
                if scriptsByPhase.isEmpty { scriptsByPhase[job.phase] = job.scriptSource }
                if paramsByPhase.isEmpty { paramsByPhase[job.phase] = job.params }
                if promptsByPhase.isEmpty { promptsByPhase[job.phase] = job.prompt }
                if resultsByPhase.isEmpty, !job.results.isEmpty {
                    resultsByPhase[job.phase] = job.results
                    ranScriptByPhase[job.phase] = job.scriptSource
                }
                prompt = promptsByPhase[job.phase] ?? ""
                scriptText = scriptsByPhase[job.phase] ?? ""
                paramsDraft = paramsByPhase[job.phase] ?? [:]
                logs = job.logs
                auditEvents = job.auditEvents
                plannedActions = job.plannedActions ?? [:]
                jobState = job.state ?? [:]
                prTitle = job.prTitle ?? ""
                canaryRepo = job.canaryRepo ?? ""
                statusLine = job.lastRunStatus ?? "Restored previous job"
            }
        }
        if !restoredJob {
            loadGoldenRecipe()
        }
    }

    private static func byPhase<T>(_ raw: [String: T]?) -> [JobPhase: T] {
        guard let raw else { return [:] }
        var mapped: [JobPhase: T] = [:]
        for (key, value) in raw {
            if let phase = JobPhase(rawValue: key) { mapped[phase] = value }
        }
        return mapped
    }

    private static func rawKeyed<T>(_ map: [JobPhase: T]) -> [String: T] {
        Dictionary(uniqueKeysWithValues: map.map { ($0.key.rawValue, $0.value) })
    }

    var typeCheckingAvailable: Bool { typescript != nil }
    var typeCheckerLabel: String {
        guard typescript != nil else { return "Type-check unavailable" }
        if let version = typescript?.compilerVersion { return "TypeScript \(version)" }
        return "TypeScript ready"
    }

    var selectedResult: RepoResult? {
        guard let selectedRepo else { return nil }
        if let result = results.first(where: { $0.id == selectedRepo }) { return result }
        // The update table carries check rows forward before any update run —
        // selecting one inspects its check evidence.
        if phase == .update {
            return resultsByPhase[.check]?.first { $0.id == selectedRepo }
        }
        return nil
    }

    /// The visible results were produced by a different script than the one
    /// in the editor (regenerated or edited since the run).
    var resultsAreStale: Bool {
        guard !results.isEmpty, let ran = ranScriptByPhase[phase] else { return false }
        return ran != scriptText
    }

    /// One row of the update table: the check verdict and the update outcome
    /// side by side, so the funnel (found by Check → planned by Update) is
    /// visible from the moment you switch phases — including the canary repo,
    /// before any update run has happened.
    struct UpdateRow: Identifiable {
        let repo: RepoRef
        let check: RepoResult?
        let update: RepoResult?
        var id: String { repo.fullName }
    }

    var updateRows: [UpdateRow] {
        let checks = resultsByPhase[.check] ?? []
        let updates = resultsByPhase[.update] ?? []
        var updatesByID = Dictionary(uniqueKeysWithValues: updates.map { ($0.id, $0) })
        var rows: [UpdateRow] = checks.map { check in
            let update = updatesByID.removeValue(forKey: check.id)
            return UpdateRow(repo: update?.repo ?? check.repo, check: check, update: update)
        }
        // Repos only the update run touched (e.g. a full scan with no carried
        // check results), in run order.
        for result in updates where updatesByID[result.id] != nil {
            rows.append(UpdateRow(repo: result.repo, check: nil, update: result))
        }
        return rows
    }

    /// Row count for the status footer — the update table includes carried
    /// check rows, not just update results.
    var visibleRowCount: Int {
        phase == .update ? updateRows.count : results.count
    }

    func clearResults() {
        resultsByPhase[phase] = []
        ranScriptByPhase[phase] = nil
        if phase == .update { plannedActions = [:] }
        selectedRepo = nil
        statusLine = "Results cleared"
    }

    func useAsCanary(_ repoID: String) {
        canaryRepo = repoID
        setPhase(.update)
        selectedRepo = repoID
        statusLine = "Canary set — update runs are confined to \(repoID)"
    }

    func setPhase(_ newPhase: JobPhase) {
        guard newPhase != phase else { return }
        // Each phase is a separate workspace: prompt, script, and params swap
        // together. An update workspace starts empty rather than inheriting
        // the check script.
        stashWorkspace()
        phase = newPhase
        restoreWorkspace()
        switch newPhase {
        case .check:
            statusLine = "Check phase — prompts generate read-only search scripts"
        case .update:
            statusLine = "Update phase — prompts generate dry-run update scripts (nothing reaches GitHub)"
        case .merge:
            statusLine = "Merge phase arrives in a later release"
        }
    }

    private func stashWorkspace() {
        promptsByPhase[phase] = prompt
        scriptsByPhase[phase] = scriptText
        paramsByPhase[phase] = paramsDraft
    }

    private func restoreWorkspace() {
        prompt = promptsByPhase[phase] ?? ""
        scriptText = scriptsByPhase[phase] ?? ""
        paramsDraft = paramsByPhase[phase] ?? [:]
        diagnostics = []
    }

    func loadRecipe(_ recipe: Recipe) {
        guard let source = recipe.source else { return }
        if recipe.phase != phase {
            stashWorkspace()
            phase = recipe.phase
        }
        scriptText = source
        prompt = recipe.prompt
        promptsByPhase[recipe.phase] = recipe.prompt
        scriptsByPhase[recipe.phase] = source
        diagnostics = []
        statusLine = "Loaded recipe — Check to type-check, Run to execute"
    }

    func loadRecipe(named name: String) {
        guard let recipe = RecipeCatalog.recipe(id: name) else { return }
        loadRecipe(recipe)
    }

    func loadGoldenRecipe() {
        loadRecipe(named: "find_yaml_key_value")
    }

    // MARK: Client selection

    func githubClient() -> GitHubClient {
        if settings.useFixtureGitHub { return FixtureGitHubClient.demo() }
        let credentials = self.credentials
        return LiveGitHubClient(apiHost: settings.apiHost,
                                tokenProvider: { credentials.read(.githubToken) },
                                rateLimit: rateLimit)
    }

    private func refreshQuota() {
        quotaText = settings.useFixtureGitHub ? nil : rateLimit.display
    }

    func llmClient() -> LLMClient {
        if settings.useMockLLM { return MockLLMClient() }
        let credentials = self.credentials
        return AnthropicClient(model: settings.aiModel,
                               keyProvider: { credentials.read(.anthropicAPIKey) })
    }

    // MARK: Actions

    func generate() {
        guard !generating, !prompt.isEmpty else { return }
        generating = true
        statusLine = "Requesting script… (model thinking)"
        let client = llmClient()
        let context = ScriptGenerationContext(organisation: settings.organisation, phase: phase)
        var promptText = prompt
        if phase == .update, !prTitle.isEmpty {
            promptText += "\n\nUse exactly this pull request title: \"\(prTitle)\""
        }
        let previousScript = scriptText
        Task {
            // Stream the raw response, painting the in-progress script into
            // the editor as it is written; parse the assembled text at the end.
            var raw = ""
            do {
                for try await event in client.streamScript(prompt: promptText, context: context) {
                    guard case .delta(let chunk) = event else { continue }
                    raw += chunk
                    let live = PromptLibrary.liveScript(fromPartial: raw)
                    if !live.isEmpty { scriptText = live }
                    statusLine = "Writing script… \(raw.count) characters"
                }
                switch PromptLibrary.parseGeneration(from: raw) {
                case .script(let script) where !script.isEmpty:
                    scriptText = script
                    statusLine = "Script generated — review before running"
                    generating = false
                    await validate()
                case .script:
                    scriptText = previousScript
                    statusLine = "Generation produced no script"
                    generating = false
                case .capabilityGap(let report):
                    scriptText = previousScript
                    surfaceCapabilityGap(report)
                    generating = false
                }
            } catch LLMClientError.capabilityGap(let report) {
                scriptText = previousScript
                surfaceCapabilityGap(report)
                generating = false
            } catch {
                scriptText = previousScript
                statusLine = "Generation failed: \(error.localizedDescription)"
                generating = false
            }
        }
    }

    private func surfaceCapabilityGap(_ report: String) {
        statusLine = "Capability gap — the model needs host APIs we don't offer (details in console)"
        logs.append("◆ The model reports this request needs capabilities the host API does not provide:")
        for line in report.split(separator: "\n", omittingEmptySubsequences: false) {
            logs.append("  " + String(line))
        }
    }

    @discardableResult
    func validate() async -> ValidatedScript? {
        // Join an in-flight validation (e.g. the auto-validate right after
        // generation) instead of bailing with nil — the silent nil made Run
        // a no-op the first time after regenerating a script.
        if let task = validationTask { return await task.value }
        let task = Task { await performValidation() }
        validationTask = task
        let result = await task.value
        validationTask = nil
        return result
    }

    private func performValidation() async -> ValidatedScript? {
        validating = true
        defer { validating = false }
        statusLine = typeCheckingAvailable ? "Type-checking against bulkgh.d.ts…" : "Checking…"
        let source = scriptText
        let pipeline = self.pipeline
        do {
            let validated = try await Task.detached(priority: .userInitiated) {
                try pipeline.validate(source: source)
            }.value
            diagnostics = validated.diagnostics
            var merged = validated.meta.params
            for (key, value) in paramsDraft where merged[key] != nil {
                merged[key] = value
            }
            paramsDraft = merged
            // A script declaring a different phase moves there WITH the
            // current buffer (no workspace swap): the script, prompt, and
            // params on screen belong to the declared phase now.
            phase = validated.meta.phase
            // Two-way sync with the explicit PR-title field: an explicit
            // title wins; otherwise the script's (auto)generated one shows.
            if !prTitle.isEmpty {
                if paramsDraft["prTitle"] != nil { paramsDraft["prTitle"] = prTitle }
            } else if let generated = paramsDraft["prTitle"] {
                prTitle = generated
            }
            statusLine = "Valid — \(validated.meta.title)"
            return validated
        } catch let error as ValidationError {
            diagnostics = error.diagnostics
            statusLine = error.errorDescription ?? "Validation failed"
            return nil
        } catch {
            statusLine = "Validation failed: \(error.localizedDescription)"
            return nil
        }
    }

    func run() {
        guard !running, !generating else { return }
        runTask = Task { await runInternal() }
    }

    private func runInternal() async {
        guard let validated = await validate() else { return }
        running = true
        defer { running = false }
        let runPhase = validated.meta.phase
        let runScript = scriptText
        runGeneration += 1
        let generation = runGeneration
        resultsByPhase[runPhase] = []
        logs = []
        auditEvents = []
        if runPhase == .update { plannedActions = [:] }
        statusLine = "Running…"
        var params = paramsDraft
        if runPhase == .update, !prTitle.isEmpty, params["prTitle"] != nil {
            params["prTitle"] = prTitle
        }
        var configuration = EngineConfiguration(settings: settings)
        let canary = canaryRepo.trimmingCharacters(in: .whitespaces)
        if runPhase == .update, !canary.isEmpty {
            let fullName = canary.contains("/") ? canary : "\(settings.organisation)/\(canary)"
            configuration.targetRepos = [fullName]
        }
        let outcome = await engine.run(javaScript: validated.javaScript,
                                       phase: runPhase,
                                       params: params,
                                       github: githubClient(),
                                       organisation: settings.organisation,
                                       configuration: configuration,
                                       initialState: jobState) { [weak self] event in
            Task { @MainActor [weak self] in
                guard let self, self.runGeneration == generation else { return }
                self.handle(event, phase: runPhase)
            }
        }
        // Retire stragglers before installing the final snapshot — a late
        // event hopping onto the main actor afterwards would duplicate rows
        // or log lines.
        runGeneration += 1
        resultsByPhase[runPhase] = outcome.results
        ranScriptByPhase[runPhase] = runScript
        logs = outcome.logs
        auditEvents = outcome.auditEvents
        if runPhase == .update { plannedActions = outcome.plannedActions }
        if !outcome.state.isEmpty {
            jobState.merge(outcome.state) { _, new in new }
        }
        refreshQuota()
        if let quotaText {
            logs.append("◆ GitHub \(quotaText) requests remaining")
        }
        let plannedRepos = outcome.results.filter { $0.status == .planned }
        if !plannedRepos.isEmpty {
            // Keep the user's selection (e.g. the canary they were
            // inspecting); only auto-select when nothing was chosen.
            if selectedRepo == nil { selectedRepo = plannedRepos.first?.id }
            statusLine = "Run \(outcome.status.label) — \(plannedRepos.count) repo(s) planned; dry-run diffs in the right panel"
        } else {
            statusLine = "Run \(outcome.status.label)"
        }
        saveNow()
    }

    func cancel() {
        runTask?.cancel()
        statusLine = "Cancelling…"
    }

    private func handle(_ event: RunEvent, phase runPhase: JobPhase) {
        switch event {
        case .log(let line):
            logs.append(line)
        case .progress(let line):
            logs.append("▸ \(line)")
        case .repo(let result):
            var rows = resultsByPhase[runPhase] ?? []
            if let index = rows.firstIndex(where: { $0.id == result.id }) {
                rows[index] = result
            } else {
                rows.append(result)
            }
            resultsByPhase[runPhase] = rows
        case .audit(let event):
            auditEvents.append(event)
            refreshQuota()
        }
    }

    // MARK: Persistence

    func saveNow() {
        stashWorkspace()
        var job = Job(prompt: prompt, phase: phase)
        job.scriptSource = scriptText
        job.params = paramsDraft
        job.results = results
        job.resultsByPhase = Self.rawKeyed(resultsByPhase)
        job.ranScriptByPhase = Self.rawKeyed(ranScriptByPhase)
        job.scriptsByPhase = Self.rawKeyed(scriptsByPhase)
        job.paramsByPhase = Self.rawKeyed(paramsByPhase)
        job.logs = logs
        job.auditEvents = auditEvents
        job.plannedActions = plannedActions
        job.state = jobState
        job.prTitle = prTitle
        job.canaryRepo = canaryRepo
        job.promptsByPhase = Self.rawKeyed(promptsByPhase)
        job.lastRunStatus = statusLine
        try? store.save(AppStateSnapshot(settings: settings, job: job))
    }
}
