#!/bin/bash
# Assembles dist/BulkGitHub.app from the Xcode project (generated by XcodeGen;
# see project.yml).
#
# Built with xcodebuild rather than `swift build` + hand assembly: SwiftPM's
# generated Bundle.module accessor for executable products probes only the
# app-bundle ROOT (where codesign forbids loose bundles) and the absolute
# build-time path, so a hand-assembled app fatalErrors at launch on every
# machine except the one that built it — for our Kit bundle and Highlightr's
# alike. Xcode's accessor probes Contents/Resources, where xcodebuild embeds
# every package resource bundle.
#
# Ad-hoc signed for local use; CI release signing/notarization is separate
# (see .github/workflows/release.yml).
set -euo pipefail
cd "$(dirname "$0")/.."

CONFIG="${1:-release}"
APP="dist/BulkGitHub.app"
VERSION="${VERSION:-0.4.4}"
DERIVED=".build/DerivedData"

case "$CONFIG" in
  release) XCODE_CONFIG="Release" ;;
  debug)   XCODE_CONFIG="Debug" ;;
  *) echo "unknown config: $CONFIG (use release|debug)" >&2; exit 1 ;;
esac

xcodebuild -project BulkGitHub.xcodeproj -scheme BulkGitHubApp \
  -configuration "$XCODE_CONFIG" -derivedDataPath "$DERIVED" \
  MARKETING_VERSION="$VERSION" CURRENT_PROJECT_VERSION="$VERSION" \
  build

BUILT="$DERIVED/Build/Products/$XCODE_CONFIG/BulkGitHub.app"
[[ -d "$BUILT" ]] || { echo "missing $BUILT" >&2; exit 1; }
# Where the Xcode-generated Bundle.module accessor will look at runtime.
[[ -d "$BUILT/Contents/Resources/BulkGitHub_BulkGitHubKit.bundle" ]] || {
  echo "BulkGitHubKit resource bundle not embedded in app" >&2; exit 1
}
[[ -d "$BUILT/Contents/Resources/Highlightr_Highlightr.bundle" ]] || {
  echo "Highlightr resource bundle not embedded in app" >&2; exit 1
}

rm -rf "$APP"
mkdir -p dist
ditto "$BUILT" "$APP"

codesign --force --sign - "$APP"
echo "Built $APP (config: $XCODE_CONFIG, version: $VERSION)"
