import SwiftUI
import CodeEditor
import BulkGitHubKit

struct ScriptPane: View {
    @Environment(AppModel.self) private var model
    @Environment(\.colorScheme) private var colorScheme

    var body: some View {
        @Bindable var model = model
        VStack(spacing: 6) {
            if model.phase != .check {
                WriteModeBanner()
            }
            // The prompt is the user's words — what they recognise the job
            // by — so it gets visual primacy over the generated code.
            HStack(alignment: .top, spacing: 8) {
                TextField(promptPlaceholder,
                          text: $model.prompt, axis: .vertical)
                    .lineLimit(2...4)
                    .font(.system(size: 15))
                    .textFieldStyle(.roundedBorder)
                    .onSubmit { model.generate() }
                Button(model.generating ? "Generating…" : "Generate") {
                    model.generate()
                }
                .controlSize(.large)
                .disabled(model.generating || model.running || model.prompt.isEmpty)
            }
            .padding([.top, .horizontal], 10)

            if model.phase == .update {
                VStack(spacing: 6) {
                    HStack(spacing: 8) {
                        TextField("PR title (autogenerated when empty)", text: $model.prTitle)
                            .textFieldStyle(.roundedBorder)
                        TextField("Canary repo — run against one repo first (optional)",
                                  text: $model.canaryRepo)
                            .textFieldStyle(.roundedBorder)
                            .frame(maxWidth: 280)
                            .help("owner/name or bare repo name; right-click a results row to set it")
                    }
                    TextField("PR description (autogenerated when empty)",
                              text: $model.prBody, axis: .vertical)
                        .lineLimit(1...3)
                        .textFieldStyle(.roundedBorder)
                }
                .font(.callout)
                .padding(.horizontal, 10)
            }

            CodeEditor(source: $model.scriptText,
                       language: .typescript,
                       theme: colorScheme == .dark ? .atelierSavannaDark : .atelierSavannaLight,
                       inset: CGSize(width: 8, height: 8))
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .padding(.horizontal, 10)

            if !model.visibleParamKeys.isEmpty {
                ParamsBar()
                    .padding(.horizontal, 10)
            }

            if !model.diagnostics.isEmpty {
                DiagnosticsList()
                    .frame(maxHeight: 110)
                    .padding(.horizontal, 10)
            }

            HStack {
                if model.running || model.validating || model.generating {
                    ProgressView()
                        .controlSize(.small)
                }
                Text(model.statusLine)
                    .font(.callout)
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
                    .truncationMode(.tail)
                Spacer()
                Text("\(model.visibleRowCount) repos")
                    .font(.callout)
                    .foregroundStyle(.tertiary)
            }
            .padding([.horizontal, .bottom], 10)
        }
    }

    private var promptPlaceholder: String {
        switch model.phase {
        case .check: return "Describe what to find across the organisation…"
        case .update: return "Describe the change to make across matching repos…"
        case .merge: return "Describe the merge or cancel action for this job's PRs…"
        }
    }
}

/// Reflects the user-set run mode (the Dry Run / Write toggle) — a real mode,
/// not an implication of which button exists. Purple for dry run, red the
/// moment Write is selected, louder still while an armed run executes.
struct WriteModeBanner: View {
    @Environment(AppModel.self) private var model

    private var target: String {
        model.settings.useFixtureGitHub ? "fixture data" : "LIVE GitHub (org \(model.settings.organisation))"
    }

    var body: some View {
        HStack(spacing: 8) {
            if model.currentRunIsArmed {
                Image(systemName: "bolt.fill")
                Text("WRITING — the reviewed plan is being applied to \(target)")
                    .fontWeight(.semibold)
            } else if model.writeArmed {
                Image(systemName: "bolt.fill")
                Text("WRITE MODE — \"Apply…\" runs the reviewed plan against \(target) for the repos you select")
                    .fontWeight(.semibold)
            } else {
                Image(systemName: "shield.lefthalf.filled")
                Text(model.settings.useFixtureGitHub
                        ? "DRY RUN — writes are recorded as a reviewable plan; nothing reaches GitHub"
                        : "DRY RUN — writes are recorded as a reviewable plan; reads come from live GitHub, nothing is written")
            }
            Spacer()
        }
        .font(.callout)
        .foregroundStyle(isWrite ? Color.red : Color.purple)
        .padding(.horizontal, 12)
        .padding(.vertical, 5)
        .frame(maxWidth: .infinity)
        .background((isWrite ? Color.red : Color.purple).opacity(isWrite ? 0.14 : 0.10))
        .overlay(alignment: .bottom) { Divider() }
    }

    private var isWrite: Bool { model.writeArmed || model.currentRunIsArmed }
}

/// Editable parameters surfaced from the script's meta.params — tweak a job
/// without re-prompting or editing code. A wrapping grid of labelled fields:
/// nothing crops off-screen, however many params a script declares.
struct ParamsBar: View {
    @Environment(AppModel.self) private var model

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            Label("Script parameters", systemImage: "slider.horizontal.3")
                .font(.caption)
                .foregroundStyle(.secondary)
                .help("Editable values from the script's meta.params")

            LazyVGrid(columns: [GridItem(.adaptive(minimum: 200, maximum: 380),
                                         spacing: 8, alignment: .topLeading)],
                      alignment: .leading, spacing: 8) {
                ForEach(model.visibleParamKeys, id: \.self) { key in
                    VStack(alignment: .leading, spacing: 2) {
                        Text(key)
                            .font(.caption2)
                            .foregroundStyle(.secondary)
                        TextField(key, text: binding(for: key))
                            .textFieldStyle(.roundedBorder)
                            .font(.system(.caption, design: .monospaced))
                    }
                }
            }
        }
        .padding(8)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(.quaternary.opacity(0.3), in: RoundedRectangle(cornerRadius: 6))
    }

    private func binding(for key: String) -> Binding<String> {
        Binding(
            get: { model.paramsDraft[key] ?? "" },
            set: { model.paramsDraft[key] = $0 }
        )
    }
}

struct DiagnosticsList: View {
    @Environment(AppModel.self) private var model

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 2) {
                ForEach(model.diagnostics) { diagnostic in
                    HStack(alignment: .firstTextBaseline, spacing: 6) {
                        Image(systemName: icon(for: diagnostic.severity))
                            .foregroundStyle(color(for: diagnostic.severity))
                            .font(.caption)
                        if diagnostic.line > 0 {
                            Text("\(diagnostic.line):\(diagnostic.column)")
                                .font(.system(.caption, design: .monospaced))
                                .foregroundStyle(.secondary)
                        }
                        Text(diagnostic.message)
                            .font(.caption)
                            .textSelection(.enabled)
                        Spacer()
                    }
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(6)
        }
        .background(.quaternary.opacity(0.4), in: RoundedRectangle(cornerRadius: 6))
    }

    private func icon(for severity: Diagnostic.Severity) -> String {
        switch severity {
        case .error: return "xmark.octagon.fill"
        case .warning: return "exclamationmark.triangle.fill"
        case .info: return "info.circle"
        }
    }

    private func color(for severity: Diagnostic.Severity) -> Color {
        switch severity {
        case .error: return .red
        case .warning: return .orange
        case .info: return .secondary
        }
    }
}
