const meta: ScriptMeta = {
  title: "Append a section to a file (dry-run update)",
  phase: "update",
  apiVersion: 1,
  params: {
    path: "README.md",
    heading: "# License",
    body: "TBD",
    branch: "bulkgh/add-license-section",
    message: "Add License section",
    prTitle: "Add License section",
    prBody: "Adds a # License section. Generated by BulkGitHub; review the diff before merging.",
  },
};

/** Appends the section with one blank line between blocks and a trailing newline. */
function appendSection(text: string, heading: string, body: string): string {
  const trimmed = text.replace(/\s*$/, "");
  return `${trimmed}\n\n${heading}\n\n${body}\n`;
}

/** Re-fetches the file (contents must be current), plans branch/edit/PR. */
async function planRepo(repoName: string, defaultBranch: string): Promise<void> {
  const { path, heading, body, branch, message, prTitle, prBody } = job.params;

  const text = await gh.getContent(repoName, path);
  if (text === null) {
    job.skip(repoName, `${path} absent`);
    return;
  }
  if (text.includes(heading)) {
    job.skip(repoName, `already contains "${heading}"`);
    return;
  }

  let ref = await gh.getRef(repoName, `heads/${defaultBranch}`);
  if (ref === null) {
    // Carried state can hold a wrong branch (defaults are a mix of master and
    // main across the org) — resolve the authoritative one and retry once.
    const repo = await gh.getRepo(repoName);
    if (repo.defaultBranch !== defaultBranch) {
      defaultBranch = repo.defaultBranch;
      ref = await gh.getRef(repoName, `heads/${defaultBranch}`);
    }
  }
  if (ref === null) {
    job.error(repoName, `default branch ${defaultBranch} has no ref`);
    return;
  }
  await gh.createBranch(repoName, branch, ref.sha);
  await gh.putContent(repoName, path, appendSection(text, heading, body), { branch, message });
  await gh.createPR(repoName, { head: branch, title: prTitle, body: prBody });
  job.log(`${repoName}: section planned`);
}

async function main(): Promise<void> {
  const { path, heading } = job.params;

  // Prefer the check phase's recorded matches: no repeat of the org-wide
  // scan; only the matched repos are re-fetched for fresh diffs.
  const prior = job.readState("missingMarker") as
    { repo: string; defaultBranch: string }[] | null;

  if (prior !== null && prior.length > 0) {
    job.progress(`planning updates for ${prior.length} repo(s) carried over from the check run`);
    for (const match of prior) {
      try {
        await planRepo(match.repo, match.defaultBranch);
      } catch (e) {
        job.error(match.repo, String(e));
      }
    }
  } else {
    const repos = await gh.listOrgRepos();
    job.progress(`no check results to carry over — scanning ${repos.length} repo(s) for ${path} missing "${heading}"`);
    for (const repo of repos) {
      if (repo.archived) {
        job.skip(repo, "archived");
        continue;
      }
      try {
        await planRepo(repo.fullName, repo.defaultBranch);
      } catch (e) {
        job.error(repo, String(e));
      }
    }
  }

  job.progress("dry run complete — review the plan per repo");
}
