const meta: ScriptMeta = {
  title: "Add a file from an attached local file",
  phase: "update",
  apiVersion: 1,
  prompt: "Add a file I supply to every repository that doesn't already have it",
  params: {
    path: ".github/workflows/ci.yml",
    contentFile: "",
    branch: "bulkgh/add-file",
    message: "Add file",
    prTitle: "Add file",
    prBody: "Adds a file from an attached local source. Generated by BulkGitHub; review the diff before merging.",
  },
};

/**
 * Creates `path` in every repository where it is absent, with the EXACT bytes
 * of the file attached to the `contentFile` param (the app shows a picker for
 * any param ending in "File"; job.file returns the picked file's content —
 * job.params.contentFile carries only its name). Repositories that already
 * have the path are skipped untouched, whatever their content — replacing an
 * existing file is a different, deliberate task.
 */
async function main(): Promise<void> {
  const { path, branch, message, prTitle, prBody } = job.params;
  // At the TOP of main, outside the per-repo loop: a wrong key fails the
  // whole run immediately instead of erroring every repo.
  const content = job.file("contentFile");

  const repos = await gh.listOrgRepos();
  const active = repos.filter(repo => !repo.archived);
  repos.filter(repo => repo.archived).forEach(repo => job.skip(repo, "archived"));
  job.progress(`checking ${active.length} repo(s) for ${path}`);

  // One batched existence probe instead of a getContent per repo. Batch
  // trade-off: null means absent OR fetch-failed — a false "absent" fails
  // safe later, at the armed drift guard.
  const texts = await gh.getContentBatch(active.map(repo => ({ repo, path })));

  for (let i = 0; i < active.length; i++) {
    const repo = active[i];
    const existing = texts[i];
    if (existing !== null) {
      job.skip(repo, existing === content
        ? `${path} already present with identical content`
        : `${path} already exists (with different content) — not replaced`);
      continue;
    }
    try {
      const ref = await gh.getRef(repo.fullName, `heads/${repo.defaultBranch}`);
      if (ref === null) {
        job.error(repo, `default branch ${repo.defaultBranch} has no ref`);
        continue;
      }
      await gh.createBranch(repo.fullName, branch, ref.sha);
      await gh.putContent(repo.fullName, path, content, { branch, message });
      await gh.createPR(repo.fullName, { head: branch, title: prTitle, body: prBody });
      job.log(`${repo.fullName}: ${path} planned`);
    } catch (e) {
      job.error(repo, String(e));
    }
  }

  job.progress("dry run complete — review the all-added diffs per repo");
}
