const meta: ScriptMeta = {
  title: "Change a YAML value under a glob (dry-run update)",
  phase: "update",
  apiVersion: 1,
  params: {
    glob: "deploy/**",
    extensions: "yml,yaml,template",
    key: "RetentionInDays",
    from: "14",
    to: "30",
    branch: "bulkgh/change-retention-days",
    message: "Change RetentionInDays from 14 to 30",
    prTitle: "Change log retention from 14 to 30 days",
    prBody: "Changes RetentionInDays from 14 to 30. Generated by BulkGitHub; review the diff before merging.",
  },
};

/** Escape a literal for use inside a RegExp. */
function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Rewrites `key: from` lines to `key: to`, preserving indentation, quoting
 * style, and trailing comments. The edit is line-level on purpose: a
 * parse-and-reserialize round trip would destroy formatting, comments, and
 * CloudFormation tags (!Ref, !GetAtt, …), making the diff unreviewable.
 */
function changeValueLines(text: string, key: string, from: string, to: string): string {
  const pattern = new RegExp(
    `^(\\s*${escapeRegExp(key)}\\s*:\\s*)(["']?)${escapeRegExp(from)}\\2(\\s*(?:#.*)?)$`);
  return text.split("\n").map(line => {
    const match = line.match(pattern);
    if (match === null) return line;
    return `${match[1]}${match[2]}${to}${match[2]}${match[3]}`;
  }).join("\n");
}

/** Plans branch/edits/PR for one repo's changed files. */
async function planRepo(repoName: string, defaultBranch: string,
                        edits: { path: string; updated: string }[]): Promise<void> {
  const { branch, message, prTitle, prBody } = job.params;

  let ref = await gh.getRef(repoName, `heads/${defaultBranch}`);
  if (ref === null) {
    // Defaults are a mix of master and main across the org — resolve the
    // authoritative one and retry once.
    const repo = await gh.getRepo(repoName);
    if (repo.defaultBranch !== defaultBranch) {
      defaultBranch = repo.defaultBranch;
      ref = await gh.getRef(repoName, `heads/${defaultBranch}`);
    }
  }
  if (ref === null) {
    job.error(repoName, `default branch ${defaultBranch} has no ref`);
    return;
  }
  await gh.createBranch(repoName, branch, ref.sha);
  for (const edit of edits) {
    await gh.putContent(repoName, edit.path, edit.updated, { branch, message });
  }
  await gh.createPR(repoName, { head: branch, title: prTitle, body: prBody });
  job.log(`${repoName}: ${edits.length} file(s) planned`);
}

async function main(): Promise<void> {
  const { glob, extensions, key, from, to } = job.params;
  const suffixes = extensions.split(",").map(e => "." + e.trim());

  const repos = await gh.listOrgRepos();
  job.progress(`scanning ${repos.length} repo(s) for ${key}: ${from} under ${glob} (${extensions})`);
  for (const repo of repos) {
    if (repo.archived) {
      job.skip(repo, "archived");
      continue;
    }
    try {
      const files = await gh.listFiles(repo, glob);
      const yamlFiles = files.filter(path => suffixes.some(s => path.endsWith(s)));
      if (yamlFiles.length === 0) {
        job.skip(repo, `no ${extensions} files matching ${glob}`);
        continue;
      }
      const edits: { path: string; updated: string }[] = [];
      for (const path of yamlFiles) {
        const text = await gh.getContent(repo, path);
        if (text === null) continue;
        const updated = changeValueLines(text, key, from, to);
        if (updated !== text) edits.push({ path, updated });
      }
      if (edits.length === 0) {
        job.skip(repo, `${key}: ${from} not found under ${glob}`);
        continue;
      }
      await planRepo(repo.fullName, repo.defaultBranch, edits);
    } catch (e) {
      job.error(repo, String(e));
    }
  }

  job.progress("dry run complete — review the plan per repo");
}
