const meta: ScriptMeta = {
  title: "Delete lines between markers (dry-run update)",
  phase: "update",
  apiVersion: 1,
  params: {
    glob: "deploy/**",
    startMarker: "# >>>",
    endMarker: "# <<<",
    branch: "bulkgh/delete-marked-block",
    message: "Delete marked block",
    prTitle: "Delete marked block",
    prBody: "Deletes the lines from the start marker to the next end marker, both inclusive. Generated by BulkGitHub; review the diff before merging.",
  },
};

/**
 * Removes every block from a line containing startMarker through the next
 * line containing endMarker, both marker lines included. An unterminated
 * block is left untouched — deleting to end-of-file on a missing end
 * marker is never the intended edit.
 */
function removeMarkedBlocks(text: string, startMarker: string, endMarker: string): string {
  const lines = text.split("\n");
  const kept: string[] = [];
  let i = 0;
  while (i < lines.length) {
    if (!lines[i].includes(startMarker)) {
      kept.push(lines[i]);
      i++;
      continue;
    }
    let end = -1;
    for (let j = i + 1; j < lines.length; j++) {
      if (lines[j].includes(endMarker)) {
        end = j;
        break;
      }
    }
    if (end === -1) {
      for (let j = i; j < lines.length; j++) kept.push(lines[j]);
      break;
    }
    i = end + 1;
  }
  return kept.join("\n");
}

/** Plans branch/edits/PR for one repo's marked files. */
async function planRepo(repoName: string, defaultBranch: string,
                        edits: { path: string; updated: string }[]): Promise<void> {
  const { branch, message, prTitle, prBody } = job.params;

  let ref = await gh.getRef(repoName, `heads/${defaultBranch}`);
  if (ref === null) {
    // Defaults are a mix of master and main across the org — resolve the
    // authoritative one and retry once.
    const repo = await gh.getRepo(repoName);
    if (repo.defaultBranch !== defaultBranch) {
      defaultBranch = repo.defaultBranch;
      ref = await gh.getRef(repoName, `heads/${defaultBranch}`);
    }
  }
  if (ref === null) {
    job.error(repoName, `default branch ${defaultBranch} has no ref`);
    return;
  }
  await gh.createBranch(repoName, branch, ref.sha);
  for (const edit of edits) {
    await gh.putContent(repoName, edit.path, edit.updated, { branch, message });
  }
  await gh.createPR(repoName, { head: branch, title: prTitle, body: prBody });
  job.log(`${repoName}: ${edits.length} file(s) planned`);
}

async function main(): Promise<void> {
  const { glob, startMarker, endMarker } = job.params;

  const repos = await gh.listOrgRepos();
  job.progress(`scanning ${repos.length} repo(s) for ${startMarker} … ${endMarker} blocks under ${glob}`);
  for (const repo of repos) {
    if (repo.archived) {
      job.skip(repo, "archived");
      continue;
    }
    try {
      const files = await gh.listFiles(repo, glob);
      if (files.length === 0) {
        job.skip(repo, `no files matching ${glob}`);
        continue;
      }
      const edits: { path: string; updated: string }[] = [];
      for (const path of files) {
        const text = await gh.getContent(repo, path);
        if (text === null || !text.includes(startMarker)) continue;
        const updated = removeMarkedBlocks(text, startMarker, endMarker);
        if (updated !== text) edits.push({ path, updated });
      }
      if (edits.length === 0) {
        job.skip(repo, `no marked blocks under ${glob}`);
        continue;
      }
      await planRepo(repo.fullName, repo.defaultBranch, edits);
    } catch (e) {
      job.error(repo, String(e));
    }
  }

  job.progress("dry run complete — review the plan per repo");
}
