const meta: ScriptMeta = {
  title: "Delete lines containing a string (dry-run update)",
  phase: "update",
  apiVersion: 1,
  params: {
    glob: "deploy/**",
    needle: "ec2-shell-prod-eu-west-1-keypair-1",
    branch: "bulkgh/remove-keypair-reference",
    message: "Remove retired keypair reference",
    prTitle: "Remove retired keypair reference",
    prBody: "Deletes the line referencing the retired keypair. Generated by BulkGitHub; review the diff before merging.",
  },
};

/**
 * Removes every line containing the needle. For JSON, repairs the dangling
 * comma a deletion can leave behind: a well-formed document had no trailing
 * commas, so any line now ending with a comma directly before a closing
 * bracket was caused by the removal.
 */
function removeLinesContaining(text: string, needle: string, isJson: boolean): string {
  const kept = text.split("\n").filter(line => !line.includes(needle));
  if (isJson) {
    for (let i = 0; i + 1 < kept.length; i++) {
      if (/,\s*$/.test(kept[i]) && /^\s*[}\]]/.test(kept[i + 1])) {
        kept[i] = kept[i].replace(/,\s*$/, "");
      }
    }
  }
  return kept.join("\n");
}

/** Re-fetches each file (contents must be current), plans branch/edits/PR. */
async function planRepo(repoName: string, defaultBranch: string, paths: string[]): Promise<void> {
  const { needle, branch, message, prTitle, prBody } = job.params;

  const edits: { path: string; updated: string }[] = [];
  for (const path of paths) {
    const text = await gh.getContent(repoName, path);
    if (text === null || !text.includes(needle)) continue;
    edits.push({ path, updated: removeLinesContaining(text, needle, path.endsWith(".json")) });
  }
  if (edits.length === 0) {
    job.skip(repoName, "string no longer present");
    return;
  }

  let ref = await gh.getRef(repoName, `heads/${defaultBranch}`);
  if (ref === null) {
    // Carried state can hold a wrong branch (defaults are a mix of master and
    // main across the org) — resolve the authoritative one and retry once.
    const repo = await gh.getRepo(repoName);
    if (repo.defaultBranch !== defaultBranch) {
      defaultBranch = repo.defaultBranch;
      ref = await gh.getRef(repoName, `heads/${defaultBranch}`);
    }
  }
  if (ref === null) {
    job.error(repoName, `default branch ${defaultBranch} has no ref`);
    return;
  }
  await gh.createBranch(repoName, branch, ref.sha);
  for (const edit of edits) {
    await gh.putContent(repoName, edit.path, edit.updated, { branch, message });
  }
  await gh.createPR(repoName, { head: branch, title: prTitle, body: prBody });
  job.log(`${repoName}: ${edits.length} file(s) planned`);
}

async function main(): Promise<void> {
  const { glob, needle } = job.params;

  // Prefer the check phase's recorded matches: no repeat of the org-wide
  // search; only the matched files are re-fetched for fresh diffs.
  const prior = job.readState("stringMatches") as
    { repo: string; defaultBranch: string; paths: string[] }[] | null;

  if (prior !== null && prior.length > 0) {
    job.progress(`planning updates for ${prior.length} repo(s) carried over from the check run`);
    for (const match of prior) {
      try {
        await planRepo(match.repo, match.defaultBranch, match.paths);
      } catch (e) {
        job.error(match.repo, String(e));
      }
    }
  } else {
    const repos = await gh.listOrgRepos();
    job.progress(`no check results to carry over — scanning ${repos.length} repos for ${glob}`);
    for (const repo of repos) {
      if (repo.archived) {
        job.skip(repo, "archived");
        continue;
      }
      try {
        const files = await gh.listFiles(repo, glob);
        if (files.length === 0) {
          job.skip(repo, `no files matching ${glob}`);
          continue;
        }
        const hits: string[] = [];
        for (const path of files) {
          const text = await gh.getContent(repo, path);
          if (text !== null && text.includes(needle)) hits.push(path);
        }
        if (hits.length === 0) {
          job.skip(repo, `string not found in ${files.length} file(s) matching ${glob}`);
          continue;
        }
        await planRepo(repo.fullName, repo.defaultBranch, hits);
      } catch (e) {
        job.error(repo, String(e));
      }
    }
  }

  job.progress("dry run complete — review the plan per repo");
}
