const meta: ScriptMeta = {
  title: "Delete lines containing a string (dry-run update)",
  phase: "update",
  apiVersion: 1,
  params: {
    glob: "deploy/**",
    needle: "ec2-shell-prod-eu-west-1-keypair-1",
    branch: "bulkgh/remove-keypair-reference",
    message: "Remove retired keypair reference",
    prTitle: "Remove retired keypair reference",
    prBody: "Deletes the line referencing the retired keypair. Generated by BulkGitHub; review the diff before merging.",
  },
};

/**
 * Removes every line containing the needle. For JSON, repairs the dangling
 * comma a deletion can leave behind: a well-formed document had no trailing
 * commas, so any line now ending with a comma directly before a closing
 * bracket was caused by the removal.
 */
function removeLinesContaining(text: string, needle: string, isJson: boolean): string {
  const kept = text.split("\n").filter(line => !line.includes(needle));
  if (isJson) {
    for (let i = 0; i + 1 < kept.length; i++) {
      if (/,\s*$/.test(kept[i]) && /^\s*[}\]]/.test(kept[i + 1])) {
        kept[i] = kept[i].replace(/,\s*$/, "");
      }
    }
  }
  return kept.join("\n");
}

async function main(): Promise<void> {
  const { glob, needle, branch, message, prTitle, prBody } = job.params;

  const repos = await gh.listOrgRepos();
  job.progress(`scanning ${repos.length} repos for ${glob} files containing the string`);

  for (const repo of repos) {
    if (repo.archived) {
      job.skip(repo, "archived");
      continue;
    }
    try {
      const files = await gh.listFiles(repo, glob);
      if (files.length === 0) {
        job.skip(repo, `no files matching ${glob}`);
        continue;
      }

      const edits: { path: string; updated: string }[] = [];
      for (const path of files) {
        const text = await gh.getContent(repo, path);
        if (text === null || !text.includes(needle)) continue;
        const updated = removeLinesContaining(text, needle, path.endsWith(".json"));
        edits.push({ path, updated });
      }
      if (edits.length === 0) {
        job.skip(repo, `string not found in ${files.length} file(s) matching ${glob}`);
        continue;
      }

      const ref = await gh.getRef(repo, `heads/${repo.defaultBranch}`);
      if (ref === null) {
        job.error(repo, `default branch ${repo.defaultBranch} has no ref`);
        continue;
      }
      await gh.createBranch(repo, branch, ref.sha);
      for (const edit of edits) {
        await gh.putContent(repo, edit.path, edit.updated, { branch, message });
      }
      await gh.createPR(repo, { head: branch, title: prTitle, body: prBody });
      job.log(`${repo.fullName}: ${edits.length} file(s) planned`);
    } catch (e) {
      job.error(repo, String(e));
    }
  }

  job.progress("dry run complete — review the plan per repo");
}
